# Generated by Django 3.1.7 on 2021-04-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_1', models.CharField(max_length=255)),
                ('keyword_2', models.CharField(max_length=255)),
                ('keyword_3', models.CharField(max_length=255)),
                ('sentiment', models.CharField(max_length=255)),
            ],
        ),
    ]
