# Generated by Django 3.1.7 on 2021-04-02 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_classification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classification',
        ),
    ]
